services:
  api:
    image: node:20
    container_name: api
    working_dir: /app
    command: sh -c "npm install && npm run server"  # Installs dependencies and then starts the server
    ports:
      - "5000:5000"
    volumes:
      - "./backend:/app"             # Mount the backend directory as /app
      - "./package.json:/app/package.json" # Mount package.json separately
      - "/app/node_modules"  # Ensure node_modules remains in the container
    env_file:
      - .env
  web:
    image: node:20
    container_name: web
    working_dir: /src
    command: sh -c "npm install && npm run start"  # Installs dependencies and then starts the server
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/src"             # Mount the frontend directory as /src
      - "./frontend/package.json:/src/package.json" # Mount package.json separately
      - "/src/node_modules"  # Ensure node_modules remains in the container